name: autisociety

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: s4.serv00.com
        username: f8480_main
        password: Sonbolserv00
        protocol: ftp
        server-dir: /
        local-dir: ./